/**
 * This script is generated by I Maker
 * DO NOT MODIFY!
 */


part of lib_app_prm_dart;

class Node extends IModel {
  static String _delimiter = ':';

  static const String _name = 'Node';

  static const List _pk = const [1];
  static const List _pkColumns = const ["id"];
  static const List _listPKColumns = const ["groupId"];
  static const num _length = 6;
  static const List _columns = const [const {"i":0,"full":"groupId","abb":"gi","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},const {"i":1,"full":"id","abb":"i","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},const {"i":2,"full":"name","abb":"n","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},const {"i":3,"full":"host","abb":"h","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},const {"i":4,"full":"port","abb":"p","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},const {"i":5,"full":"password","abb":"p1","toAdd":false,"toSet":false,"toAbb":false,"toFull":false,"toList":false},];
  static const Map _mapAbb = const {"gi":0,"i":1,"n":2,"h":3,"p":4,"p1":5};
  static const Map _mapFull = const {"groupId":0,"id":1,"name":2,"host":3,"port":4,"password":5};

  List _args;
  List<bool> _updatedList;
  bool _exist = false;

  Node([List args = null]) : super() {
    if (args == null) {
      _args = new List.filled(_length, null);
    } else {
      if (args is! List) throw new IModelException(10010);
      if (args.length != _length) throw new IModelException(10009);
      _args = args;
    }
    _updatedList = new List.filled(_length, false);
  }

  String getName() => _name;
  String getColumnCount() => _length;

  Map getColumns() => _columns;
  Map getMapAbb() => _mapAbb;
  Map getMapFull() => _mapFull;

  void setExist([bool exist = true]) { _exist = exist; }
  bool isExist() => _exist;

  void setPK(idRaw) {
    id = idRaw;
  }
  getPK() => id;
  List getPKColumns() => _pkColumns;

  String getUnitedPK() {
    var pk = getPK();
    if (pk == null) throw new IModelException(10015);
    return getPK().toString();
  }
  List getListPK() => [groupId];
  List getListPKColumns() => ["groupId"];
  String getUnitedListPK() {
    List listPK = getListPK();
    if (listPK.contains(null)) throw new IModelException(10020);
    return listPK.join(_delimiter);
  }

  List getChildPK() => [id];
  String getUnitedChildPK() {
    List childPK = getChildPK();
    if (childPK.contains(null)) throw new IModelException(10018);
    return childPK.join(_delimiter);
  }

  List getWholePK() => [groupId, id];
  String getUnitedWholePK() {
    List wholePK = getWholePK();
    if (wholePK.contains(null)) throw new IModelException(10019);
    return wholePK.join(_delimiter);
  }

  void set groupId(v) {
    if (_args[0] == v) return;
    _args[0] = v;
    _updatedList[0] = true;
  }
  get groupId => _args[0];

  void set id(v) {
    if (_args[1] == v) return;
    _args[1] = v;
    _updatedList[1] = true;
  }
  get id => _args[1];

  void set name(v) {
    if (_args[2] == v) return;
    _args[2] = v;
    _updatedList[2] = true;
  }
  get name => _args[2];

  void set host(v) {
    if (_args[3] == v) return;
    _args[3] = v;
    _updatedList[3] = true;
  }
  get host => _args[3];

  void set port(v) {
    if (_args[4] == v) return;
    _args[4] = v;
    _updatedList[4] = true;
  }
  get port => _args[4];

  void set password(v) {
    if (_args[5] == v) return;
    _args[5] = v;
    _updatedList[5] = true;
  }
  get password => _args[5];

  bool isUpdated() => _updatedList.any((bool e) => e);
  void setUpdatedList(bool flag) => _updatedList.fillRange(0, _length, flag);

  List toAddFixedList([bool filterOn = false]) {
    if (!filterOn) return _args.toList(growable: false);

    List result = new List.filled(_length, null);
    for (num i = 0; i < _length; ++i) {
      if (_columns[i]['toAdd']) continue;
      result[i] = _args[i];
    }
    return result;
  }
  List toAddList([bool filterOn = false]) {
    List result = [];
    for (num i = 0; i < _length; ++i) {
      if (filterOn && _columns[i]['toAdd']) continue;
      result.add(_args[i]);
    }
    return result;
  }
  Map toAddFull([bool filterOn = false]) {
    Map result = {};
    _mapFull.forEach((full, i) {
      if (filterOn && _columns[i]['toAdd']) return;
      result[full] = _args[i];
    });
    return result;
  }
  Map toAddAbb([bool filterOn = false]) {
    Map result = {};
    _mapAbb.forEach((abb, i) {
      if (filterOn && _columns[i]['toAdd']) return;
      result[abb] = _args[i];
    });
    return result;
  }

  List toSetFixedList([bool filterOn = false]) {
    List result = new List.filled(_length, null);
    for (num i = 0; i < _length; ++i) {
      if (filterOn && _columns[i]['toSet']) continue;
      if (_updatedList[i]) result[i] = _args[i].toString();
    }
    return result;
  }
  List toSetList([bool filterOn = false]) {
    List result = [];
    for (num i = 0; i < _length; ++i) {
      if (filterOn && _columns[i]['toSet']) continue;
      if (_updatedList[i]) result.add(_args[i].toString());
    }
    return result;
  }
  Map toSetFull([bool filterOn = false]) {
    Map result = {};
    _mapFull.forEach((full, i) {
      if (filterOn && _columns[i]['toSet']) return;
      if (_updatedList[i]) result[full] = _args[i];
    });
    return result;
  }
  Map toSetAbb([bool filterOn = false]) {
    Map result = {};
    _mapAbb.forEach((abb, i) {
      if (filterOn && _columns[i]['toSet']) return;
      if (_updatedList[i]) result[abb] = _args[i];
    });
    return result;
  }

  List toFixedList([bool filterOn = false]) {
    List result = new List.filled(_length, null);
    for (num i = 0; i < _length; ++i) {
      if (filterOn && _columns[i]['toList']) continue;
      result[i] = _args[i];
    }
    return result;
  }
  List toList([bool filterOn = false]) {
    List result = [];
    for (num i = 0; i < _length; ++i) {
      if (filterOn && _columns[i]['toList']) continue;
      result.add(_args[i]);
    }
    return result;
  }
  Map toFull([bool filterOn = false]) {
    Map result = {};
    _mapFull.forEach((full, i) {
      if (filterOn && _columns[i]['toFull']) return;
      result[full] = _args[i];
    });
    return result;
  }
  Map toAbb([bool filterOn = false]) {
    Map result = {};
    _mapAbb.forEach((abb, i) {
      if (filterOn && _columns[i]['toAbb']) return;
      result[abb] = _args[i];
    });
    return result;
  }

  void fromList(List data, [bool changeUpdatedList = false]) {
    if (data is! List || data.length != _length) throw new IModelException(10006);
    for (num i = 0; i < _args.length; ++i) {
      _args[i] = data[i];
    }
    if (changeUpdatedList) setUpdatedList(true);
  }
  void fromFull(Map data, [bool changeUpdatedList = false]) {
    if (data is! Map) throw new IModelException(10008);

    _mapFull.forEach((String full, num i) {
      if (!data.containsKey(full)) return;
      _args[i] = data[full];
      if (changeUpdatedList) _updatedList[i] = true;
    });
  }
  void fromAbb(Map data, [bool changeUpdatedList = false]) {
    if (data is! Map) throw new IModelException(10007);

    _mapAbb.forEach((String abb, num i) {
      if (!data.containsKey(abb)) return;
      _args[i] = data[abb];
      if (changeUpdatedList) _updatedList[i] = true;
    });
  }
}